"""Ticket validation and deterministic priority calculation."""

VALID_CATEGORIES = {
    "network": "Network",
    "hardware": "Hardware",
    "software": "Software",
    "other": "Other",
}
VALID_URGENCIES = {"low", "medium", "high"}


def calculate_priority(urgency: str, affected_users: int) -> str:
    """Return critical/high/medium/low according to the project rules."""
    if not isinstance(urgency, str) or urgency.strip().lower() not in VALID_URGENCIES:
        raise ValueError("Urgency must be low, medium, or high.")
    if isinstance(affected_users, bool) or not isinstance(affected_users, int) or affected_users <= 0:
        raise ValueError("Affected users must be a positive integer.")

    urgency = urgency.strip().lower()
    if urgency == "high" and affected_users >= 10:
        return "critical"
    if urgency == "high" or affected_users >= 10:
        return "high"
    if urgency == "medium" or affected_users >= 3:
        return "medium"
    return "low"


def validate_ticket_data(title: str, category: str, urgency: str, affected_users: int) -> dict:
    """Validate inputs and normalize valid case variations consistently."""
    if not isinstance(title, str) or not title.strip():
        raise ValueError("Title must not be blank.")
    if not isinstance(category, str) or category.strip().lower() not in VALID_CATEGORIES:
        raise ValueError("Category must be Network, Hardware, Software, or Other.")
    if not isinstance(urgency, str):
        raise ValueError("Urgency must be low, medium, or high.")
    normalized_urgency = urgency.strip().lower()
    priority = calculate_priority(normalized_urgency, affected_users)
    return {
        "title": title.strip(),
        "category": VALID_CATEGORIES[category.strip().lower()],
        "urgency": normalized_urgency,
        "affected_users": affected_users,
        "priority": priority,
    }


def create_ticket(title: str, category: str, urgency: str, affected_users: int, ticket_id: str) -> dict:
    """Build one open ticket. The caller supplies an ID generated by workflow."""
    if not isinstance(ticket_id, str) or not ticket_id.strip():
        raise ValueError("Ticket ID must be a non-empty string.")
    fields = validate_ticket_data(title, category, urgency, affected_users)
    return {
        "id": ticket_id.strip(),
        **fields,
        "status": "open",
        "assigned_to": None,
    }
